const express = require("express");
const router = express.Router();
// const { getTracks } = require("../services/getTracks.js");
const { searchYoutube } = require("../services/searchYoutube.js");
const ytdl = require("ytdl-core");

router.get("/download/:name/:artist", async (req, res) => {
  const { name, artist } = req.params;

  //playlist
  const data = {
    href: "https://api.spotify.com/v1/playlists/6vgjOd3MVHDlKoAtYJTii6/tracks?offset=0&limit=100",
    items: [
      {
        added_at: "2022-09-17T13:15:03Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/wns0yj7jyoz4sdqy98zy43sax",
          },
          href: "https://api.spotify.com/v1/users/wns0yj7jyoz4sdqy98zy43sax",
          id: "wns0yj7jyoz4sdqy98zy43sax",
          type: "user",
          uri: "spotify:user:wns0yj7jyoz4sdqy98zy43sax",
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/2LRoIwlKmHjgvigdNGBHNo",
                },
                href: "https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo",
                id: "2LRoIwlKmHjgvigdNGBHNo",
                name: "Feid",
                type: "artist",
                uri: "spotify:artist:2LRoIwlKmHjgvigdNGBHNo",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/4hUQ4FB9GD5oDmw3XHIr0G",
            },
            href: "https://api.spotify.com/v1/albums/4hUQ4FB9GD5oDmw3XHIr0G",
            id: "4hUQ4FB9GD5oDmw3XHIr0G",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2733d7b95838b533131d1db6292",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e023d7b95838b533131d1db6292",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048513d7b95838b533131d1db6292",
                width: 64,
              },
            ],
            name: "INTER SHIBUYA - LA MAFIA",
            release_date: "2021-08-20",
            release_date_precision: "day",
            total_tracks: 15,
            type: "album",
            uri: "spotify:album:4hUQ4FB9GD5oDmw3XHIr0G",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/2LRoIwlKmHjgvigdNGBHNo",
              },
              href: "https://api.spotify.com/v1/artists/2LRoIwlKmHjgvigdNGBHNo",
              id: "2LRoIwlKmHjgvigdNGBHNo",
              name: "Feid",
              type: "artist",
              uri: "spotify:artist:2LRoIwlKmHjgvigdNGBHNo",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          disc_number: 1,
          duration_ms: 121440,
          episode: false,
          explicit: false,
          external_ids: { isrc: "USUM72107361" },
          external_urls: {
            spotify: "https://open.spotify.com/track/6GrGYZbYt9Yq8R5aiSWZ0j",
          },
          href: "https://api.spotify.com/v1/tracks/6GrGYZbYt9Yq8R5aiSWZ0j",
          id: "6GrGYZbYt9Yq8R5aiSWZ0j",
          is_local: false,
          name: "HULU",
          popularity: 49,
          preview_url: null,
          track: true,
          track_number: 10,
          type: "track",
          uri: "spotify:track:6GrGYZbYt9Yq8R5aiSWZ0j",
        },
        video_thumbnail: { url: null },
      },
      {
        added_at: "2022-09-20T09:54:38Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/wns0yj7jyoz4sdqy98zy43sax",
          },
          href: "https://api.spotify.com/v1/users/wns0yj7jyoz4sdqy98zy43sax",
          id: "wns0yj7jyoz4sdqy98zy43sax",
          type: "user",
          uri: "spotify:user:wns0yj7jyoz4sdqy98zy43sax",
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "single",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/43BxCL6t4c73BQnIJtry5v",
                },
                href: "https://api.spotify.com/v1/artists/43BxCL6t4c73BQnIJtry5v",
                id: "43BxCL6t4c73BQnIJtry5v",
                name: "James Hype",
                type: "artist",
                uri: "spotify:artist:43BxCL6t4c73BQnIJtry5v",
              },
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/45ruzGUmIr8WLjLOPJ9mGU",
                },
                href: "https://api.spotify.com/v1/artists/45ruzGUmIr8WLjLOPJ9mGU",
                id: "45ruzGUmIr8WLjLOPJ9mGU",
                name: "Miggy Dela Rosa",
                type: "artist",
                uri: "spotify:artist:45ruzGUmIr8WLjLOPJ9mGU",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/6moZ4sNThthUAwCklyuPY8",
            },
            href: "https://api.spotify.com/v1/albums/6moZ4sNThthUAwCklyuPY8",
            id: "6moZ4sNThthUAwCklyuPY8",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2736cc861b5c9c7cdef61b010b4",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e026cc861b5c9c7cdef61b010b4",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048516cc861b5c9c7cdef61b010b4",
                width: 64,
              },
            ],
            name: "Ferrari",
            release_date: "2022-04-01",
            release_date_precision: "day",
            total_tracks: 1,
            type: "album",
            uri: "spotify:album:6moZ4sNThthUAwCklyuPY8",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/43BxCL6t4c73BQnIJtry5v",
              },
              href: "https://api.spotify.com/v1/artists/43BxCL6t4c73BQnIJtry5v",
              id: "43BxCL6t4c73BQnIJtry5v",
              name: "James Hype",
              type: "artist",
              uri: "spotify:artist:43BxCL6t4c73BQnIJtry5v",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/45ruzGUmIr8WLjLOPJ9mGU",
              },
              href: "https://api.spotify.com/v1/artists/45ruzGUmIr8WLjLOPJ9mGU",
              id: "45ruzGUmIr8WLjLOPJ9mGU",
              name: "Miggy Dela Rosa",
              type: "artist",
              uri: "spotify:artist:45ruzGUmIr8WLjLOPJ9mGU",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          disc_number: 1,
          duration_ms: 186661,
          episode: false,
          explicit: false,
          external_ids: { isrc: "GB3CE2200004" },
          external_urls: {
            spotify: "https://open.spotify.com/track/4zN21mbAuaD0WqtmaTZZeP",
          },
          href: "https://api.spotify.com/v1/tracks/4zN21mbAuaD0WqtmaTZZeP",
          id: "4zN21mbAuaD0WqtmaTZZeP",
          is_local: false,
          name: "Ferrari",
          popularity: 87,
          preview_url: null,
          track: true,
          track_number: 1,
          type: "track",
          uri: "spotify:track:4zN21mbAuaD0WqtmaTZZeP",
        },
        video_thumbnail: { url: null },
      },
      {
        added_at: "2022-09-20T09:54:54Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/wns0yj7jyoz4sdqy98zy43sax",
          },
          href: "https://api.spotify.com/v1/users/wns0yj7jyoz4sdqy98zy43sax",
          id: "wns0yj7jyoz4sdqy98zy43sax",
          type: "user",
          uri: "spotify:user:wns0yj7jyoz4sdqy98zy43sax",
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "single",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/2iI5KWXLjw1tqLQsdjuo0e",
                },
                href: "https://api.spotify.com/v1/artists/2iI5KWXLjw1tqLQsdjuo0e",
                id: "2iI5KWXLjw1tqLQsdjuo0e",
                name: "Chael Produciendo",
                type: "artist",
                uri: "spotify:artist:2iI5KWXLjw1tqLQsdjuo0e",
              },
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/2oQX8QiMXOyuqbcZEFsZfm",
                },
                href: "https://api.spotify.com/v1/artists/2oQX8QiMXOyuqbcZEFsZfm",
                id: "2oQX8QiMXOyuqbcZEFsZfm",
                name: "El Alfa",
                type: "artist",
                uri: "spotify:artist:2oQX8QiMXOyuqbcZEFsZfm",
              },
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/5sZ0LIk7BJLJquEUUt5rJj",
                },
                href: "https://api.spotify.com/v1/artists/5sZ0LIk7BJLJquEUUt5rJj",
                id: "5sZ0LIk7BJLJquEUUt5rJj",
                name: "El Mayor Clasico",
                type: "artist",
                uri: "spotify:artist:5sZ0LIk7BJLJquEUUt5rJj",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/34EGyXtxsJbIL5gAFVzcZa",
            },
            href: "https://api.spotify.com/v1/albums/34EGyXtxsJbIL5gAFVzcZa",
            id: "34EGyXtxsJbIL5gAFVzcZa",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b27372224284d8267246cc057c4e",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e0272224284d8267246cc057c4e",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d0000485172224284d8267246cc057c4e",
                width: 64,
              },
            ],
            name: "GALAPIN",
            release_date: "2022-03-17",
            release_date_precision: "day",
            total_tracks: 1,
            type: "album",
            uri: "spotify:album:34EGyXtxsJbIL5gAFVzcZa",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/2oQX8QiMXOyuqbcZEFsZfm",
              },
              href: "https://api.spotify.com/v1/artists/2oQX8QiMXOyuqbcZEFsZfm",
              id: "2oQX8QiMXOyuqbcZEFsZfm",
              name: "El Alfa",
              type: "artist",
              uri: "spotify:artist:2oQX8QiMXOyuqbcZEFsZfm",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/5sZ0LIk7BJLJquEUUt5rJj",
              },
              href: "https://api.spotify.com/v1/artists/5sZ0LIk7BJLJquEUUt5rJj",
              id: "5sZ0LIk7BJLJquEUUt5rJj",
              name: "El Mayor Clasico",
              type: "artist",
              uri: "spotify:artist:5sZ0LIk7BJLJquEUUt5rJj",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/2iI5KWXLjw1tqLQsdjuo0e",
              },
              href: "https://api.spotify.com/v1/artists/2iI5KWXLjw1tqLQsdjuo0e",
              id: "2iI5KWXLjw1tqLQsdjuo0e",
              name: "Chael Produciendo",
              type: "artist",
              uri: "spotify:artist:2iI5KWXLjw1tqLQsdjuo0e",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          disc_number: 1,
          duration_ms: 196177,
          episode: false,
          explicit: false,
          external_ids: { isrc: "QM4TX2227949" },
          external_urls: {
            spotify: "https://open.spotify.com/track/29EmyYlu6tRW51iY7AvGNT",
          },
          href: "https://api.spotify.com/v1/tracks/29EmyYlu6tRW51iY7AvGNT",
          id: "29EmyYlu6tRW51iY7AvGNT",
          is_local: false,
          name: "GALAPIN",
          popularity: 53,
          preview_url:
            "https://p.scdn.co/mp3-preview/2fe086c85dafee753f73f6dcdd9c34ccea6e071a?cid=774b29d4f13844c495f206cafdad9c86",
          track: true,
          track_number: 1,
          type: "track",
          uri: "spotify:track:29EmyYlu6tRW51iY7AvGNT",
        },
        video_thumbnail: { url: null },
      },
      {
        added_at: "2022-09-20T09:55:01Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/wns0yj7jyoz4sdqy98zy43sax",
          },
          href: "https://api.spotify.com/v1/users/wns0yj7jyoz4sdqy98zy43sax",
          id: "wns0yj7jyoz4sdqy98zy43sax",
          type: "user",
          uri: "spotify:user:wns0yj7jyoz4sdqy98zy43sax",
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "single",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/2oQX8QiMXOyuqbcZEFsZfm",
                },
                href: "https://api.spotify.com/v1/artists/2oQX8QiMXOyuqbcZEFsZfm",
                id: "2oQX8QiMXOyuqbcZEFsZfm",
                name: "El Alfa",
                type: "artist",
                uri: "spotify:artist:2oQX8QiMXOyuqbcZEFsZfm",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5nk75NdvD4wH7ARj1R9u2A",
            },
            href: "https://api.spotify.com/v1/albums/5nk75NdvD4wH7ARj1R9u2A",
            id: "5nk75NdvD4wH7ARj1R9u2A",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273b5e111671be6dfb83b0a080e",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02b5e111671be6dfb83b0a080e",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851b5e111671be6dfb83b0a080e",
                width: 64,
              },
            ],
            name: "Chu Chu Pamela",
            release_date: "2022-06-21",
            release_date_precision: "day",
            total_tracks: 1,
            type: "album",
            uri: "spotify:album:5nk75NdvD4wH7ARj1R9u2A",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/2oQX8QiMXOyuqbcZEFsZfm",
              },
              href: "https://api.spotify.com/v1/artists/2oQX8QiMXOyuqbcZEFsZfm",
              id: "2oQX8QiMXOyuqbcZEFsZfm",
              name: "El Alfa",
              type: "artist",
              uri: "spotify:artist:2oQX8QiMXOyuqbcZEFsZfm",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          disc_number: 1,
          duration_ms: 177214,
          episode: false,
          explicit: false,
          external_ids: { isrc: "QM6N22255852" },
          external_urls: {
            spotify: "https://open.spotify.com/track/14pr9SjxdNW8ZGU9GdZGLh",
          },
          href: "https://api.spotify.com/v1/tracks/14pr9SjxdNW8ZGU9GdZGLh",
          id: "14pr9SjxdNW8ZGU9GdZGLh",
          is_local: false,
          name: "Chu Chu Pamela",
          popularity: 67,
          preview_url:
            "https://p.scdn.co/mp3-preview/b1c1497d2c25d9b434736c8fa327403ad3d508de?cid=774b29d4f13844c495f206cafdad9c86",
          track: true,
          track_number: 1,
          type: "track",
          uri: "spotify:track:14pr9SjxdNW8ZGU9GdZGLh",
        },
        video_thumbnail: { url: null },
      },
      {
        added_at: "2022-09-21T22:45:35Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/wns0yj7jyoz4sdqy98zy43sax",
          },
          href: "https://api.spotify.com/v1/users/wns0yj7jyoz4sdqy98zy43sax",
          id: "wns0yj7jyoz4sdqy98zy43sax",
          type: "user",
          uri: "spotify:user:wns0yj7jyoz4sdqy98zy43sax",
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "single",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/1mcTU81TzQhprhouKaTkpq",
                },
                href: "https://api.spotify.com/v1/artists/1mcTU81TzQhprhouKaTkpq",
                id: "1mcTU81TzQhprhouKaTkpq",
                name: "Rauw Alejandro",
                type: "artist",
                uri: "spotify:artist:1mcTU81TzQhprhouKaTkpq",
              },
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/7iK8PXO48WeuP03g8YR51W",
                },
                href: "https://api.spotify.com/v1/artists/7iK8PXO48WeuP03g8YR51W",
                id: "7iK8PXO48WeuP03g8YR51W",
                name: "Myke Towers",
                type: "artist",
                uri: "spotify:artist:7iK8PXO48WeuP03g8YR51W",
              },
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/51XrH5fQP2oIQynuKxSWcW",
                },
                href: "https://api.spotify.com/v1/artists/51XrH5fQP2oIQynuKxSWcW",
                id: "51XrH5fQP2oIQynuKxSWcW",
                name: "Sky Rompiendo",
                type: "artist",
                uri: "spotify:artist:51XrH5fQP2oIQynuKxSWcW",
              },
            ],
            available_markets: [
              "AD",
              "AE",
              "AG",
              "AL",
              "AM",
              "AO",
              "AR",
              "AT",
              "AU",
              "AZ",
              "BA",
              "BB",
              "BD",
              "BE",
              "BF",
              "BG",
              "BH",
              "BI",
              "BJ",
              "BN",
              "BO",
              "BR",
              "BS",
              "BT",
              "BW",
              "BY",
              "BZ",
              "CA",
              "CD",
              "CG",
              "CH",
              "CI",
              "CL",
              "CM",
              "CO",
              "CR",
              "CV",
              "CW",
              "CY",
              "CZ",
              "DE",
              "DJ",
              "DK",
              "DM",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FJ",
              "FM",
              "FR",
              "GA",
              "GB",
              "GD",
              "GE",
              "GH",
              "GM",
              "GN",
              "GQ",
              "GR",
              "GT",
              "GW",
              "GY",
              "HK",
              "HN",
              "HR",
              "HT",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IQ",
              "IS",
              "IT",
              "JM",
              "JO",
              "JP",
              "KE",
              "KG",
              "KH",
              "KI",
              "KM",
              "KN",
              "KR",
              "KW",
              "KZ",
              "LA",
              "LB",
              "LC",
              "LI",
              "LK",
              "LR",
              "LS",
              "LT",
              "LU",
              "LV",
              "LY",
              "MA",
              "MC",
              "MD",
              "ME",
              "MG",
              "MH",
              "MK",
              "ML",
              "MN",
              "MO",
              "MR",
              "MT",
              "MU",
              "MV",
              "MW",
              "MX",
              "MY",
              "MZ",
              "NA",
              "NE",
              "NG",
              "NI",
              "NL",
              "NO",
              "NP",
              "NR",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PG",
              "PH",
              "PK",
              "PL",
              "PS",
              "PT",
              "PW",
              "PY",
              "QA",
              "RO",
              "RS",
              "RW",
              "SA",
              "SB",
              "SC",
              "SE",
              "SG",
              "SI",
              "SK",
              "SL",
              "SM",
              "SN",
              "SR",
              "ST",
              "SV",
              "SZ",
              "TD",
              "TG",
              "TH",
              "TJ",
              "TL",
              "TN",
              "TO",
              "TR",
              "TT",
              "TV",
              "TW",
              "TZ",
              "UA",
              "UG",
              "US",
              "UY",
              "UZ",
              "VC",
              "VE",
              "VN",
              "VU",
              "WS",
              "XK",
              "ZA",
              "ZM",
              "ZW",
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/26DBrzosCFxgTFBzhcbDPp",
            },
            href: "https://api.spotify.com/v1/albums/26DBrzosCFxgTFBzhcbDPp",
            id: "26DBrzosCFxgTFBzhcbDPp",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273907a5a9ab6eef474aba7d86c",
                width: 640,
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02907a5a9ab6eef474aba7d86c",
                width: 300,
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851907a5a9ab6eef474aba7d86c",
                width: 64,
              },
            ],
            name: "Ponte Pa' Mi",
            release_date: "2020-04-16",
            release_date_precision: "day",
            total_tracks: 1,
            type: "album",
            uri: "spotify:album:26DBrzosCFxgTFBzhcbDPp",
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/1mcTU81TzQhprhouKaTkpq",
              },
              href: "https://api.spotify.com/v1/artists/1mcTU81TzQhprhouKaTkpq",
              id: "1mcTU81TzQhprhouKaTkpq",
              name: "Rauw Alejandro",
              type: "artist",
              uri: "spotify:artist:1mcTU81TzQhprhouKaTkpq",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/7iK8PXO48WeuP03g8YR51W",
              },
              href: "https://api.spotify.com/v1/artists/7iK8PXO48WeuP03g8YR51W",
              id: "7iK8PXO48WeuP03g8YR51W",
              name: "Myke Towers",
              type: "artist",
              uri: "spotify:artist:7iK8PXO48WeuP03g8YR51W",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/51XrH5fQP2oIQynuKxSWcW",
              },
              href: "https://api.spotify.com/v1/artists/51XrH5fQP2oIQynuKxSWcW",
              id: "51XrH5fQP2oIQynuKxSWcW",
              name: "Sky Rompiendo",
              type: "artist",
              uri: "spotify:artist:51XrH5fQP2oIQynuKxSWcW",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          disc_number: 1,
          duration_ms: 184817,
          episode: false,
          explicit: true,
          external_ids: { isrc: "QZHN22000006" },
          external_urls: {
            spotify: "https://open.spotify.com/track/10u2iOS0r6plfb9GknD7g4",
          },
          href: "https://api.spotify.com/v1/tracks/10u2iOS0r6plfb9GknD7g4",
          id: "10u2iOS0r6plfb9GknD7g4",
          is_local: false,
          name: "Ponte Pa' Mi",
          popularity: 69,
          preview_url:
            "https://p.scdn.co/mp3-preview/248bd213df4cb99729df199656f7bb2181fbf844?cid=774b29d4f13844c495f206cafdad9c86",
          track: true,
          track_number: 1,
          type: "track",
          uri: "spotify:track:10u2iOS0r6plfb9GknD7g4",
        },
        video_thumbnail: { url: null },
      },
    ],
    limit: 100,
    next: null,
    offset: 0,
    previous: null,
    total: 5,
  };

  const searched = await searchYoutube({ name, artist });

  res.header(
    "Content-Disposition",
    `attachment; filename="${name} - ${artist}.mp3`
  );
  // console.log(name, artist)
  ytdl(searched.link, { format: "mp3", quality: "lowestaudio" }).pipe(res);
});

module.exports = router;
